apiVersion: skaffold/v2beta18
kind: Config
profiles:
  - name: dev
    build:
      local:
        push: true # true: 서버 테스트 / false: 로컬 테스트
      artifacts:
        - image: feet312/apidoc-aggregator # on dev server
        #- image: apidoc-aggregator   # local
          jib:
            args:
              - -DskipTests
              - "-Djib.container.environment=SPRING_PROFILES_ACTIVE=dev"
            fromImage: openjdk:11.0.11-jre-slim
    deploy:
      kubectl:
        manifests:
         
          - k8s/dev/apidoc-*.yaml 
portForward:
   - resourceType: Service
     resourceName: apidoc-aggregator-service
     namespace: apidoc-aggregator
     port: 8080
     localPort: 8080 # *Optional*